ENH: Use `str` instead of `Path` for `_parse_yaml_config` parameter
Use `str` instead of `Path` for `_parse_yaml_config` parameter since
`argparse` passes the argument as a string, not as a `Path`.

Fixes:
```
src/nifreeze/cli/parser.py:74: error:
 Argument "type" to "add_argument" of "_ActionsContainer" has incompatible type
 "Callable[[Path], dict[Any, Any]]"; expected "Callable[[str], Any] | FileType | str"  [arg-type]
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/12437972140/job/34728973936#step:8:47