ENH: Instantiate `namedtuple` using the correct syntax for `ImageFrid`
Instantiate `namedtuple` using the correct syntax for `ImageFrid`:
`namedtuple` expects positional arguments for its fields, not keyword
argumentsi: define the `namedtuple` first and then instantiate it.

Fixes:
```
src/nifreeze/registration/ants.py:475: error:
 Unexpected keyword argument "shape" for "tuple"  [call-arg]
.tox/typecheck/lib/python3.12/site-packages/mypy/typeshed/stdlib/builtins.pyi:873:
 note: "tuple" defined here
src/nifreeze/registration/ants.py:475: error:
 Unexpected keyword argument "affine" for "tuple"  [call-arg]
.tox/typecheck/lib/python3.12/site-packages/mypy/typeshed/stdlib/builtins.pyi:873:
 note: "tuple" defined here
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/12437972140/job/34728973936#step:8:134